services:
  db: 
    container_name: '2026-06-16'
    image: postgres:17
    ports:
    - '3000:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
    volumes:
      - './db:/var/lib/postgresql/data'
